version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5-browsers
    steps:
      - checkout
      - run: node test.js
      - store_artifacts:
          path: out
          destination: test-results